pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=KEINOS
      - base=main
      - title~=^Changes
      - files=go.mod
      - files=go.sum
      - "#files=2"
      - check-success=CodeQL / Analyze (go) (pull_request)
      - check-success=Codecov / build (pull_request)
      - check-success=UnitTests / Unit test (ubuntu-latest) (pull_request)
      - check-success=UnitTests / Unit test (macos-latest) (pull_request)
      - check-success=UnitTests / Unit test (windows-latest) (pull_request)
      - check-success=Code scanning results / CodeQL
      - check-success=codecov/patch
      - check-success=codecov/project
    actions:
      merge:
        method: merge