pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=KEINOS
      - base=main
      - title~=^Changes
      - files=go.mod
      - files=go.sum
      - "#files=2"
      - check-success=Codecov
      - check-success=CodeQL
      - check-success=UnitTests
    actions:
      merge:
        method: merge