pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=KEINOS
      - base=main
      - title~=^Changes
      - files=go.mod
      - files=go.sum
      - "#files=2"
      - check-success=codecov/patch
      - check-success=codecov/project
      - check-success=CodeQL
      - check-success=build (pull_request)
      - check-success=Analyze (go) (pull_request)
      - check-success~=^Unit test (ubuntu-latest)
      - check-success~=^Unit test (macos-latest)
      - check-success~=^Unit test (windows-latest)
    actions:
      merge:
        method: merge