name: UnitTests

on:
  workflow_dispatch:
  pull_request:

jobs:
  coverage:
    name: Unit test

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Run coverage (Windows)
        if: runner.os == 'Windows'
        run: |
          go mod download
          go test -v ./...

      - name: Run coverage (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          go mod download
          go test -v ./...
